Merge from eCos master repository on 2001-05-18-01:30:05-BST

diff --git a/host/configure b/host/configure
--- a/host/configure
+++ b/host/configure
@@ -35,9 +35,9 @@ ac_help="$ac_help
 ac_help="$ac_help
  --with-tcl-version=<vsn> version of Tcl to be used"
 ac_help="$ac_help
- --with-tcl-header=<path>        location of Tcl header"
+ --with-tcl-header=<path> location of Tcl header"
 ac_help="$ac_help
- --with-tcl-lib=<path>        location of Tcl libraries"
+ --with-tcl-lib=<path>    location of Tcl libraries"
 ac_help="$ac_help
  --with-tcl=<path>        location of Tcl header and libraries"
 
@@ -1414,22 +1414,38 @@ fi
 
     fi
 
-    if test "${GCC}" = "yes" ; then
-        CC="$CC -Wall -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs"
-        CXX="$CXX -Wall -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Woverloaded-virtual"
+        if test "${GCC}" = "yes" ; then
+        cyg_CFLAGS="-pipe -Wall -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs"
+        cyg_CXXFLAGS="-pipe -Wall -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Woverloaded-virtual"
     elif test "${MSVC}" = "yes" ; then
-        CC="$CC -nologo -W3"
-        CXX="$CXX -nologo -W3 -GR -GX"
-        if test "${cygflags_enable_debug}" = "yes" ; then
-            CC="$CC -MDd -Zi"
-            CXX="$CXX -MDd -Zi"
-        else
-            CC="$CC -MD -O2"
-            CXX="$CXX -MD -O2"
-        fi
+        cyg_CFLAGS="-nologo -W3"
+        cyg_CXXFLAGS="-nologo -W3 -GR -GX"
     else
         { echo "configure: error: "default flags for ${CC} are not known"" 1>&2; exit 1; }
     fi
+
+        if test "${cygflags_enable_debug}" = "yes" ; then
+        if test "${GCC}" = "yes" ; then
+            cyg_CFLAGS="${cyg_CFLAGS} -g -O0"
+            cyg_CXXFLAGS="${cyg_CXXFLAGS} -g -O0"
+        elif test "${MSVC}" = "yes" ; then
+            cyg_CFLAGS="${cyg_CFLAGS} -MDd -Zi"
+            cyg_CXXFLAGS="${cyg_CXXFLAGS} -MDd -Zi"
+        fi
+    else
+        if test "${GCC}" = "yes" ; then
+            cyg_CFLAGS="${cyg_CFLAGS} -O0"
+            cyg_CXXFLAGS="${cyg_CXXFLAGS} -O0"
+        elif test "${MSVC}" = "yes" ; then
+            cyg_CFLAGS="${cyg_CFLAGS} -MD -O2"
+            cyg_CXXFLAGS="${cyg_CXXFLAGS} -MD -O2"
+        fi
+    fi
+
+    CFLAGS="${ac_save_CFLAGS}"
+    CXXFLAGS="${ac_save_CXXFLAGS}"
+    
+    
     echo "$ac_t""done" 1>&6
 
 
@@ -1582,7 +1598,7 @@ fi
 
 
 echo $ac_n "checking for Tcl version""... $ac_c" 1>&6
-echo "configure:1586: checking for Tcl version" >&5
+echo "configure:1602: checking for Tcl version" >&5
 # Check whether --with-tcl-version or --without-tcl-version was given.
 if test "${with_tcl_version+set}" = set; then
   withval="$with_tcl_version"
@@ -1627,10 +1643,32 @@ fi
 
 
 echo $ac_n "checking for Tcl installation""... $ac_c" 1>&6
-echo "configure:1631: checking for Tcl installation" >&5
+echo "configure:1647: checking for Tcl installation" >&5
 
-tcl_incdirs="${with_tcl_header} ${with_tcl}/include ${prefix}/include /usr/include/tcl$cyg_ac_tcl_version /usr/include"
 
+if test "${MSVC}" = "yes" ; then
+  if test "${with_tcl_header+set}" = set; then
+    cyg_ac_tcl_incdir=${with_tcl_header}
+  else
+    if test "${with_tcl+set}" = set; then
+      cyg_ac_tcl_incdir="${with_tcl}/include"
+    else
+      { echo "configure: error: You must specify a Tcl installation with either --with-tcl=<path> or --with-tcl-header=<path>" 1>&2; exit 1; }
+    fi
+  fi
+  if test "${with_tcl_lib+set}" = set; then
+    cyg_ac_tcl_libdir=${with_tcl_lib}
+  else
+    if test "${with_tcl+set}" = set; then
+      cyg_ac_tcl_libdir="${with_tcl}/lib"
+    else
+      { echo "configure: error: You must specify a Tcl installation with either --with-tcl=<path> or --with-tcl-lib=<path>" 1>&2; exit 1; }
+    fi
+  fi
+  cyg_ac_tcl_libs="tcl${cyg_ac_tcl_version}.lib"
+else
+  tcl_incdirs="${with_tcl_header} ${with_tcl}/include ${prefix}/include /usr/include/tcl$cyg_ac_tcl_version /usr/include"
+  
 cyg_ac_tcl_incdir=NO
 for i in $tcl_incdirs;
 do
@@ -1643,13 +1681,8 @@ do
   done
 done
 
-
-if test \! -r ${cyg_ac_tcl_incdir}/tcl.h ; then
-  { echo "configure: error: unable to locate Tcl header file tcl.h" 1>&2; exit 1; }
-fi
-
-tcl_libdirs="${with_tcl_lib} ${with_tcl}/lib ${prefix}/lib /usr/lib/tcl$cyg_ac_tcl_version /usr/lib"
-
+  tcl_libdirs="${with_tcl_lib} ${with_tcl}/lib ${libdir} ${prefix}/lib /usr/lib/tcl$cyg_ac_tcl_version /usr/lib"
+  
 cyg_ac_tcl_libdir=NO
 for i in $tcl_libdirs;
 do
@@ -1662,11 +1695,19 @@ do
   done
 done
 
+  if test \! -r ${cyg_ac_tcl_libdir}/tclConfig.sh ; then
+    { echo "configure: error: unable to locate Tcl config file tclConfig.sh" 1>&2; exit 1; }
+  else
+    . ${cyg_ac_tcl_libdir}/tclConfig.sh
+    cyg_ac_tcl_libs="-ltcl${cyg_ac_tcl_version} ${TCL_LIBS}"
+  fi
+fi
 
-echo "$ac_t""${cyg_ac_tcl_libdir}" 1>&6
+if test \! -r ${cyg_ac_tcl_incdir}/tcl.h ; then
+  { echo "configure: error: unable to locate Tcl header file tcl.h" 1>&2; exit 1; }
+fi
 
 if test "${MSVC}" = "yes" ; then
-  cyg_ac_tcl_libs="tcl${cyg_ac_tcl_version}.lib"
   
     
     
@@ -1683,14 +1724,9 @@ if test "${MSVC}" = "yes" ; then
       cyg_ac_tcl_libdir=`cygpath -w ${cyg_ac_tcl_libdir} | tr \\\\\\\\ /`
     fi
 
-else
-  if test \! -r ${cyg_ac_tcl_libdir}/tclConfig.sh ; then
-    { echo "configure: error: unable to locate Tcl config file tclConfig.sh" 1>&2; exit 1; }
-  else
-    . ${cyg_ac_tcl_libdir}/tclConfig.sh
-    cyg_ac_tcl_libs="-ltcl${cyg_ac_tcl_version} ${TCL_LIBS}"
-  fi
 fi
+
+echo "$ac_t""${cyg_ac_tcl_libdir}" 1>&6
 
 
 
@@ -1699,9 +1735,6 @@ fi
 
 
 ECOS_DIRS="infra libcdl"
-
-
-
 
 
 
@@ -1883,6 +1916,8 @@ s%@OBJEXT@%$OBJEXT%g
 s%@EXEEXT@%$EXEEXT%g
 s%@MSVC_TRUE@%$MSVC_TRUE%g
 s%@MSVC_FALSE@%$MSVC_FALSE%g
+s%@cyg_CFLAGS@%$cyg_CFLAGS%g
+s%@cyg_CXXFLAGS@%$cyg_CXXFLAGS%g
 s%@cyg_ac_tcl_version@%$cyg_ac_tcl_version%g
 s%@cyg_ac_tcl_incdir@%$cyg_ac_tcl_incdir%g
 s%@cyg_ac_tcl_libdir@%$cyg_ac_tcl_libdir%g
diff --git a/host/infra/configure b/host/infra/configure
--- a/host/infra/configure
+++ b/host/infra/configure
@@ -21,9 +21,9 @@ ac_help="$ac_help
 ac_help="$ac_help
  --with-tcl-version=<vsn> version of Tcl to be used"
 ac_help="$ac_help
- --with-tcl-header=<path>        location of Tcl header"
+ --with-tcl-header=<path> location of Tcl header"
 ac_help="$ac_help
- --with-tcl-lib=<path>        location of Tcl libraries"
+ --with-tcl-lib=<path>    location of Tcl libraries"
 ac_help="$ac_help
  --with-tcl=<path>        location of Tcl header and libraries"
 ac_help="$ac_help
@@ -1442,34 +1442,50 @@ fi
 
     fi
 
-    if test "${GCC}" = "yes" ; then
-        CC="$CC -Wall -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs"
-        CXX="$CXX -Wall -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Woverloaded-virtual"
+        if test "${GCC}" = "yes" ; then
+        cyg_CFLAGS="-pipe -Wall -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs"
+        cyg_CXXFLAGS="-pipe -Wall -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Woverloaded-virtual"
     elif test "${MSVC}" = "yes" ; then
-        CC="$CC -nologo -W3"
-        CXX="$CXX -nologo -W3 -GR -GX"
-        if test "${cygflags_enable_debug}" = "yes" ; then
-            CC="$CC -MDd -Zi"
-            CXX="$CXX -MDd -Zi"
-        else
-            CC="$CC -MD -O2"
-            CXX="$CXX -MD -O2"
-        fi
+        cyg_CFLAGS="-nologo -W3"
+        cyg_CXXFLAGS="-nologo -W3 -GR -GX"
     else
         { echo "configure: error: "default flags for ${CC} are not known"" 1>&2; exit 1; }
     fi
+
+        if test "${cygflags_enable_debug}" = "yes" ; then
+        if test "${GCC}" = "yes" ; then
+            cyg_CFLAGS="${cyg_CFLAGS} -g -O0"
+            cyg_CXXFLAGS="${cyg_CXXFLAGS} -g -O0"
+        elif test "${MSVC}" = "yes" ; then
+            cyg_CFLAGS="${cyg_CFLAGS} -MDd -Zi"
+            cyg_CXXFLAGS="${cyg_CXXFLAGS} -MDd -Zi"
+        fi
+    else
+        if test "${GCC}" = "yes" ; then
+            cyg_CFLAGS="${cyg_CFLAGS} -O0"
+            cyg_CXXFLAGS="${cyg_CXXFLAGS} -O0"
+        elif test "${MSVC}" = "yes" ; then
+            cyg_CFLAGS="${cyg_CFLAGS} -MD -O2"
+            cyg_CXXFLAGS="${cyg_CXXFLAGS} -MD -O2"
+        fi
+    fi
+
+    CFLAGS="${ac_save_CFLAGS}"
+    CXXFLAGS="${ac_save_CXXFLAGS}"
+    
+    
     echo "$ac_t""done" 1>&6
 
 
 echo $ac_n "checking whether byte ordering is bigendian""... $ac_c" 1>&6
-echo "configure:1466: checking whether byte ordering is bigendian" >&5
+echo "configure:1482: checking whether byte ordering is bigendian" >&5
 if eval "test \"`echo '$''{'ac_cv_c_bigendian'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   ac_cv_c_bigendian=unknown
 # See if sys/param.h defines the BYTE_ORDER macro.
 cat > conftest.$ac_ext <<EOF
-#line 1473 "configure"
+#line 1489 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <sys/param.h>
@@ -1480,11 +1496,11 @@ int main() {
 #endif
 ; return 0; }
 EOF
-if { (eval echo configure:1484: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1500: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   # It does; now see whether it defined to BIG_ENDIAN or not.
 cat > conftest.$ac_ext <<EOF
-#line 1488 "configure"
+#line 1504 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <sys/param.h>
@@ -1495,7 +1511,7 @@ int main() {
 #endif
 ; return 0; }
 EOF
-if { (eval echo configure:1499: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1515: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_c_bigendian=yes
 else
@@ -1515,7 +1531,7 @@ if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 1519 "configure"
+#line 1535 "configure"
 #include "confdefs.h"
 main () {
   /* Are we little or big endian?  From Harbison&Steele.  */
@@ -1528,7 +1544,7 @@ main () {
   exit (u.c[sizeof (long) - 1] == 1);
 }
 EOF
-if { (eval echo configure:1532: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1548: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ac_cv_c_bigendian=no
 else
@@ -1557,7 +1573,7 @@ fi
     
 
     echo $ac_n "checking "for a 64 bit data type"""... $ac_c" 1>&6
-echo "configure:1561: checking "for a 64 bit data type"" >&5
+echo "configure:1577: checking "for a 64 bit data type"" >&5
 if eval "test \"`echo '$''{'cyg_ac_cv_type_64bit'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1575,7 +1591,7 @@ cross_compiling=$ac_cv_prog_cc_cross
   ctype_64bit="long long"
 else
   cat > conftest.$ac_ext <<EOF
-#line 1579 "configure"
+#line 1595 "configure"
 #include "confdefs.h"
 
                 main() {
@@ -1583,7 +1599,7 @@ else
                 }
 	    
 EOF
-if { (eval echo configure:1587: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1603: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ctype_64bit=$type
 else
@@ -1606,10 +1622,10 @@ cross_compiling=$ac_cv_prog_cxx_cross
   cxxtype_64bit="long long"
 else
   cat > conftest.$ac_ext <<EOF
-#line 1610 "configure"
+#line 1626 "configure"
 #include "confdefs.h"
 #ifdef __cplusplus
-extern "C" void exit(int);
+extern "C" void exit(int) throw();
 #endif
 
                 int main(int argc, char ** argv) {
@@ -1617,7 +1633,7 @@ extern "C" void exit(int);
                 }
 	    
 EOF
-if { (eval echo configure:1621: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1637: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   cxxtype_64bit=$type
 else
@@ -1662,7 +1678,7 @@ EOF
 
 
 echo $ac_n "checking size of int *""... $ac_c" 1>&6
-echo "configure:1666: checking size of int *" >&5
+echo "configure:1682: checking size of int *" >&5
 if eval "test \"`echo '$''{'ac_cv_sizeof_int_p'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1670,7 +1686,7 @@ else
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 1674 "configure"
+#line 1690 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1681,7 +1697,7 @@ main()
   exit(0);
 }
 EOF
-if { (eval echo configure:1685: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1701: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ac_cv_sizeof_int_p=`cat conftestval`
 else
@@ -1701,7 +1717,7 @@ EOF
 
 
 echo $ac_n "checking size of long""... $ac_c" 1>&6
-echo "configure:1705: checking size of long" >&5
+echo "configure:1721: checking size of long" >&5
 if eval "test \"`echo '$''{'ac_cv_sizeof_long'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1709,7 +1725,7 @@ else
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 1713 "configure"
+#line 1729 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 main()
@@ -1720,7 +1736,7 @@ main()
   exit(0);
 }
 EOF
-if { (eval echo configure:1724: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:1740: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   ac_cv_sizeof_long=`cat conftestval`
 else
@@ -1745,7 +1761,7 @@ EOF
     
 
     echo $ac_n "checking "for __PRETTY_FUNCTION__ support"""... $ac_c" 1>&6
-echo "configure:1749: checking "for __PRETTY_FUNCTION__ support"" >&5
+echo "configure:1765: checking "for __PRETTY_FUNCTION__ support"" >&5
 if eval "test \"`echo '$''{'cyg_ac_cv_c_pretty_function'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1759,14 +1775,14 @@ ac_link='${CC-cc} -o conftest${ac_exeext} $CFLAGS $CPPFLAGS $LDFLAGS conftest.$a
 cross_compiling=$ac_cv_prog_cc_cross
 
         cat > conftest.$ac_ext <<EOF
-#line 1763 "configure"
+#line 1779 "configure"
 #include "confdefs.h"
 #include <stdio.h>
 int main() {
 puts(__PRETTY_FUNCTION__);
 ; return 0; }
 EOF
-if { (eval echo configure:1770: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1786: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   c_ok="yes"
 else
@@ -1785,14 +1801,14 @@ ac_link='${CXX-g++} -o conftest${ac_exeext} $CXXFLAGS $CPPFLAGS $LDFLAGS conftes
 cross_compiling=$ac_cv_prog_cxx_cross
 
         cat > conftest.$ac_ext <<EOF
-#line 1789 "configure"
+#line 1805 "configure"
 #include "confdefs.h"
 #include <cstdio>
 int main() {
 puts(__PRETTY_FUNCTION__);
 ; return 0; }
 EOF
-if { (eval echo configure:1796: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1812: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   cxx_ok="yes"
 else
@@ -1832,7 +1848,7 @@ EOF
 
 
 echo $ac_n "checking for Tcl version""... $ac_c" 1>&6
-echo "configure:1836: checking for Tcl version" >&5
+echo "configure:1852: checking for Tcl version" >&5
 # Check whether --with-tcl-version or --without-tcl-version was given.
 if test "${with_tcl_version+set}" = set; then
   withval="$with_tcl_version"
@@ -1877,10 +1893,32 @@ fi
 
 
 echo $ac_n "checking for Tcl installation""... $ac_c" 1>&6
-echo "configure:1881: checking for Tcl installation" >&5
+echo "configure:1897: checking for Tcl installation" >&5
 
-tcl_incdirs="${with_tcl_header} ${with_tcl}/include ${prefix}/include /usr/include/tcl$cyg_ac_tcl_version /usr/include"
 
+if test "${MSVC}" = "yes" ; then
+  if test "${with_tcl_header+set}" = set; then
+    cyg_ac_tcl_incdir=${with_tcl_header}
+  else
+    if test "${with_tcl+set}" = set; then
+      cyg_ac_tcl_incdir="${with_tcl}/include"
+    else
+      { echo "configure: error: You must specify a Tcl installation with either --with-tcl=<path> or --with-tcl-header=<path>" 1>&2; exit 1; }
+    fi
+  fi
+  if test "${with_tcl_lib+set}" = set; then
+    cyg_ac_tcl_libdir=${with_tcl_lib}
+  else
+    if test "${with_tcl+set}" = set; then
+      cyg_ac_tcl_libdir="${with_tcl}/lib"
+    else
+      { echo "configure: error: You must specify a Tcl installation with either --with-tcl=<path> or --with-tcl-lib=<path>" 1>&2; exit 1; }
+    fi
+  fi
+  cyg_ac_tcl_libs="tcl${cyg_ac_tcl_version}.lib"
+else
+  tcl_incdirs="${with_tcl_header} ${with_tcl}/include ${prefix}/include /usr/include/tcl$cyg_ac_tcl_version /usr/include"
+  
 cyg_ac_tcl_incdir=NO
 for i in $tcl_incdirs;
 do
@@ -1893,13 +1931,8 @@ do
   done
 done
 
-
-if test \! -r ${cyg_ac_tcl_incdir}/tcl.h ; then
-  { echo "configure: error: unable to locate Tcl header file tcl.h" 1>&2; exit 1; }
-fi
-
-tcl_libdirs="${with_tcl_lib} ${with_tcl}/lib ${prefix}/lib /usr/lib/tcl$cyg_ac_tcl_version /usr/lib"
-
+  tcl_libdirs="${with_tcl_lib} ${with_tcl}/lib ${libdir} ${prefix}/lib /usr/lib/tcl$cyg_ac_tcl_version /usr/lib"
+  
 cyg_ac_tcl_libdir=NO
 for i in $tcl_libdirs;
 do
@@ -1912,11 +1945,19 @@ do
   done
 done
 
+  if test \! -r ${cyg_ac_tcl_libdir}/tclConfig.sh ; then
+    { echo "configure: error: unable to locate Tcl config file tclConfig.sh" 1>&2; exit 1; }
+  else
+    . ${cyg_ac_tcl_libdir}/tclConfig.sh
+    cyg_ac_tcl_libs="-ltcl${cyg_ac_tcl_version} ${TCL_LIBS}"
+  fi
+fi
 
-echo "$ac_t""${cyg_ac_tcl_libdir}" 1>&6
+if test \! -r ${cyg_ac_tcl_incdir}/tcl.h ; then
+  { echo "configure: error: unable to locate Tcl header file tcl.h" 1>&2; exit 1; }
+fi
 
 if test "${MSVC}" = "yes" ; then
-  cyg_ac_tcl_libs="tcl${cyg_ac_tcl_version}.lib"
   
     
     
@@ -1933,14 +1974,9 @@ if test "${MSVC}" = "yes" ; then
       cyg_ac_tcl_libdir=`cygpath -w ${cyg_ac_tcl_libdir} | tr \\\\\\\\ /`
     fi
 
-else
-  if test \! -r ${cyg_ac_tcl_libdir}/tclConfig.sh ; then
-    { echo "configure: error: unable to locate Tcl config file tclConfig.sh" 1>&2; exit 1; }
-  else
-    . ${cyg_ac_tcl_libdir}/tclConfig.sh
-    cyg_ac_tcl_libs="-ltcl${cyg_ac_tcl_version} ${TCL_LIBS}"
-  fi
 fi
+
+echo "$ac_t""${cyg_ac_tcl_libdir}" 1>&6
 
 
 
@@ -2128,6 +2164,8 @@ s%@OBJEXT@%$OBJEXT%g
 s%@EXEEXT@%$EXEEXT%g
 s%@MSVC_TRUE@%$MSVC_TRUE%g
 s%@MSVC_FALSE@%$MSVC_FALSE%g
+s%@cyg_CFLAGS@%$cyg_CFLAGS%g
+s%@cyg_CXXFLAGS@%$cyg_CXXFLAGS%g
 s%@cyg_ac_tcl_version@%$cyg_ac_tcl_version%g
 s%@cyg_ac_tcl_incdir@%$cyg_ac_tcl_incdir%g
 s%@cyg_ac_tcl_libdir@%$cyg_ac_tcl_libdir%g
